version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # Weekdays
    reviewers:
      - "GaryGSC"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Weekdays
    reviewers:
      - "GaryGSC"
