version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # Weekdays
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Weekdays
