name: 'Terraform Plan Analyzer'
description: 'Analyzes Terraform Plan with Divvycloud'
author: 'Brigham Young University'
inputs:
  terraform-plan-file:
    required: true
    description: File name of the terraform plan
  working-directory:
    required: false
    description: Directory of the terraform configuration
    default: .
  divvycloud-password:
    required: true
    description: Password for Divvycloud
  divvycloud-username:
    required: true
    description: Username for Divvycloud
  divvycloud-URL:
    required: true
    description: URL for Divvycloud
runs:
  using: 'node12'
  main: 'dist/index.js'