name: "Test"
on:
  pull_request:
  push:
    branches:
      - staging
      - 'v*'
env:
  aws_account: "887069801155"
  aws_gha_role: "gha-tf-plan-analyzer-org-gha"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      tf_version: 1.3.3
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::${{ env.aws_account }}:role/${{ env.aws_gha_role }}"
        role-session-name: ${{ github.sha }}
        aws-region: us-west-2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Terraform Init
      run: terraform init
      working-directory: __tests__

    - name: Terraform Plan
      run: terraform plan -out test-plan.tfplan
      working-directory: __tests__

    - name: Analyze Terraform Plan
      uses: ./
      with:
        working-directory: ./__tests__
        terraform-plan-file: test-plan.tfplan
        divvycloud-username: ${{ secrets.DIVVYCLOUD_USERNAME }}
        divvycloud-password: ${{ secrets.DIVVYCLOUD_PASSWORD}}
