name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      tf_version: 0.13.0
    steps:
    - name: Check Out
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BYU_ORG_SERVICE_KEY }}
        aws-secret-access-key: ${{ secrets.BYU_ORG_SERVICE_SECRET }}
        aws-region: us-west-2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Terraform Init
      run: terraform init
      working-directory: __tests__

    - name: Terraform Plan
      run: terraform plan -out test-plan.tfplan
      working-directory: __tests__

    - name: Analyze Terraform Plan
      uses: ./
      with:
        working-directory: ./__tests__
        terraform-plan-file: test-plan.tfplan
        divvycloud-username: ${{ secrets.DIVVYCLOUD_USERNAME }}
        divvycloud-password: ${{ secrets.DIVVYCLOUD_PASSWORD}}
